cputemp: version 1.5

diff --git a/modules/cputemp b/modules/cputemp
--- a/modules/cputemp
+++ b/modules/cputemp
@@ -25,6 +25,19 @@ format=" {temp}°C"
 # Enable
 has_threshold=1
 
+# Depending on the conditions in your custom_action()
+# you can force the output to be critical or warning
+# Set these vars to 1 (in custom_action)
+force_crit=0
+force_warn=0
+
+
+# Depending on the conditions in your custom_action()
+# you can force the output to be critical or warning
+# Set these vars to 1 (in custom_action)
+force_crit=0
+force_warn=0
+
 
 ###
 ### Additional arguments
@@ -296,7 +309,7 @@ print_usage() {
 }
 
 print_version() {
-	echo "${appname} v1.3 by cytopia"
+	echo "${appname} v1.5 by cytopia"
 	echo "https://github.com/cytopia/i3blocks-modules"
 }
 
@@ -314,6 +327,21 @@ get_status_color() {
 	local _color="${_color_def}"
 
 	local pval
+
+	# has custom critical color?
+	if [ "${force_crit}" = "1" ]; then
+		_color="${_color_crit}"
+		echo "${_color}"
+		return
+	fi
+	# has custom warning color?
+	if [ "${force_warn}" = "1" ]; then
+		_color="${_color_warn}"
+		echo "${_color}"
+		return
+	fi
+
+
 
 	# has good color?
 	for (( i=0; i < ${#tg_placeholder[@]}; i++ )); do
@@ -384,6 +412,8 @@ get_status_color() {
 			fi
 		fi
 	done
+
+
 	# has critical color?
 	for (( i=0; i < ${#tc_placeholder[@]}; i++ )); do
 
@@ -407,6 +437,7 @@ get_status_color() {
 			fi
 		fi
 	done
+
 
 	echo "${_color}"
 }
@@ -474,6 +505,7 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg <p> - no placeholder specified."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			f=0
@@ -485,6 +517,7 @@ while [ $# -gt 0  ]; do
 			done
 			if [ "${f}" = "0" ]; then
 				echo "Error, -tg '${1}' no such placeholder."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			tg_placeholder+=("${format_vars[$i]}")
@@ -493,10 +526,12 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg '${tg_placeholder[${#tg_placeholder[@]}]}' '${1}' - sign is empty."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ]; then
 				echo "Error, -tg '${tg_placeholder[${#tg_placeholder[@]}]}' '${1}' - invalid sign: '${1}'."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			tg_sign+=("${1}")
@@ -505,11 +540,13 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg '${tg_placeholder[${#tg_placeholder[@]}]}' '${tg_sign[${#tg_sign[@]}]}' '${1}' - value is empty."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			if [ "${tg_sign[${#tg_sign[@]}-1]}" != "=" ]; then
 				if ! printf "%d" "${1}" >/dev/null 2>&1; then
 					echo "Error, -tg '${tg_placeholder[${#tg_placeholder[@]}]}' '${tg_sign[${#tg_sign[@]}]}' '${1}' is not a number."
+					echo "Type ${appname} -h for help"
 					exit 1
 				fi
 			fi
@@ -523,6 +560,7 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg <p> - no placeholder specified."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			f=0
@@ -534,6 +572,7 @@ while [ $# -gt 0  ]; do
 			done
 			if [ "${f}" = "0" ]; then
 				echo "Error, -tg '${1}' no such placeholder."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			ti_placeholder+=("${format_vars[$i]}")
@@ -542,10 +581,12 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg '${ti_placeholder[${#ti_placeholder[@]}]}' '${1}' - sign is empty."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ]; then
 				echo "Error, -tg '${ti_placeholder[${#ti_placeholder[@]}]}' '${1}' - invalid sign: '${1}'."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			ti_sign+=("${1}")
@@ -554,11 +595,13 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg '${ti_placeholder[${#ti_placeholder[@]}]}' '${ti_sign[${#ti_sign[@]}]}' '${1}' - value is empty."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			if [ "${ti_sign[${#ti_sign[@]}-1]}" != "=" ]; then
 				if ! printf "%d" "${1}" >/dev/null 2>&1; then
 					echo "Error, -tg '${ti_placeholder[${#ti_placeholder[@]}]}' '${ti_sign[${#ti_sign[@]}]}' '${1}' is not a number."
+					echo "Type ${appname} -h for help"
 					exit 1
 				fi
 			fi
@@ -572,6 +615,7 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg <p> - no placeholder specified."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			f=0
@@ -583,6 +627,7 @@ while [ $# -gt 0  ]; do
 			done
 			if [ "${f}" = "0" ]; then
 				echo "Error, -tg '${1}' no such placeholder."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			tw_placeholder+=("${format_vars[$i]}")
@@ -591,10 +636,12 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg '${tw_placeholder[${#tw_placeholder[@]}]}' '${1}' - sign is empty."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ]; then
 				echo "Error, -tg '${tw_placeholder[${#tw_placeholder[@]}]}' '${1}' - invalid sign: '${1}'."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			tw_sign+=("${1}")
@@ -603,11 +650,13 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg '${tw_placeholder[${#tw_placeholder[@]}]}' '${tw_sign[${#tw_sign[@]}]}' '${1}' - value is empty."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			if [ "${tw_sign[${#tw_sign[@]}-1]}" != "=" ]; then
 				if ! printf "%d" "${1}" >/dev/null 2>&1; then
 					echo "Error, -tg '${tw_placeholder[${#tw_placeholder[@]}]}' '${tw_sign[${#tw_sign[@]}]}' '${1}' is not a number."
+					echo "Type ${appname} -h for help"
 					exit 1
 				fi
 			fi
@@ -621,6 +670,7 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg <p> - no placeholder specified."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			f=0
@@ -632,6 +682,7 @@ while [ $# -gt 0  ]; do
 			done
 			if [ "${f}" = "0" ]; then
 				echo "Error, -tg '${1}' no such placeholder."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			tc_placeholder+=("${format_vars[$i]}")
@@ -640,10 +691,12 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg '${tc_placeholder[${#tc_placeholder[@]}]}' '${1}' - sign is empty."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ]; then
 				echo "Error, -tg '${tc_placeholder[${#tc_placeholder[@]}]}' '${1}' - invalid sign: '${1}'."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			tc_sign+=("${1}")
@@ -652,11 +705,13 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg '${tc_placeholder[${#tc_placeholder[@]}]}' '${tc_sign[${#tc_sign[@]}]}' '${1}' - value is empty."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			if [ "${tc_sign[${#tc_sign[@]}-1]}" != "=" ]; then
 				if ! printf "%d" "${1}" >/dev/null 2>&1; then
 					echo "Error, -tg '${tc_placeholder[${#tc_placeholder[@]}]}' '${tc_sign[${#tc_sign[@]}]}' '${1}' is not a number."
+					echo "Type ${appname} -h for help"
 					exit 1
 				fi
 			fi
@@ -667,6 +722,11 @@ while [ $# -gt 0  ]; do
 		###
 		-f)
 			shift
+			if [ "${1}" = "" ]; then
+				echo "Error, -f requires a string"
+				echo "Type ${appname} -h for help"
+				exit 1
+			fi
 			format="${1}"
 			;;
 		###
@@ -683,6 +743,7 @@ while [ $# -gt 0  ]; do
 			shift
 			if ! echo "${1}" | grep -qE '#[0-9a-fA-F]{6}' >/dev/null 2>&1; then
 				echo "Error, invalid color string: ${1}"
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			color_def="${1}"
@@ -692,6 +753,7 @@ while [ $# -gt 0  ]; do
 			shift
 			if ! echo "${1}" | grep -qE '#[0-9a-fA-F]{6}' >/dev/null 2>&1; then
 				echo "Error, invalid color string: ${1}"
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			color_good="${1}"
@@ -701,6 +763,7 @@ while [ $# -gt 0  ]; do
 			shift
 			if ! echo "${1}" | grep -qE '#[0-9a-fA-F]{6}' >/dev/null 2>&1; then
 				echo "Error, invalid color string: ${1}"
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			color_warn="${1}"
@@ -710,6 +773,7 @@ while [ $# -gt 0  ]; do
 			shift
 			if ! echo "${1}" | grep -qE '#[0-9a-fA-F]{6}' >/dev/null 2>&1; then
 				echo "Error, invalid color string: ${1}"
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			color_crit="${1}"
@@ -719,6 +783,7 @@ while [ $# -gt 0  ]; do
 			shift
 			if ! echo "${1}" | grep -qE '#[0-9a-fA-F]{6}' >/dev/null 2>&1; then
 				echo "Error, invalid color string: ${1}"
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			color_info="${1}"
@@ -760,7 +825,7 @@ while [ $# -gt 0  ]; do
 			###
 			if [ "${found}" = "0" ]; then
 				echo "Invalid argument: '${1}'"
-				print_usage
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			;;
