disk: version 1.5

diff --git a/modules/disk b/modules/disk
--- a/modules/disk
+++ b/modules/disk
@@ -25,6 +25,12 @@ format=" {free} {funit}iB free"
 # Enable
 has_threshold=1
 
+# Depending on the conditions in your custom_action()
+# you can force the output to be critical or warning
+# Set these vars to 1 (in custom_action)
+force_crit=0
+force_warn=0
+
 
 ###
 ### Additional arguments
@@ -324,7 +330,7 @@ print_usage() {
 }
 
 print_version() {
-	echo "${appname} v1.3 by cytopia"
+	echo "${appname} v1.5 by cytopia"
 	echo "https://github.com/cytopia/i3blocks-modules"
 }
 
@@ -342,6 +348,21 @@ get_status_color() {
 	local _color="${_color_def}"
 
 	local pval
+
+	# has custom critical color?
+	if [ "${force_crit}" = "1" ]; then
+		_color="${_color_crit}"
+		echo "${_color}"
+		return
+	fi
+	# has custom warning color?
+	if [ "${force_warn}" = "1" ]; then
+		_color="${_color_warn}"
+		echo "${_color}"
+		return
+	fi
+
+
 
 	# has good color?
 	for (( i=0; i < ${#tg_placeholder[@]}; i++ )); do
@@ -412,6 +433,8 @@ get_status_color() {
 			fi
 		fi
 	done
+
+
 	# has critical color?
 	for (( i=0; i < ${#tc_placeholder[@]}; i++ )); do
 
@@ -435,6 +458,7 @@ get_status_color() {
 			fi
 		fi
 	done
+
 
 	echo "${_color}"
 }
@@ -502,6 +526,7 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg <p> - no placeholder specified."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			f=0
@@ -513,6 +538,7 @@ while [ $# -gt 0  ]; do
 			done
 			if [ "${f}" = "0" ]; then
 				echo "Error, -tg '${1}' no such placeholder."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			tg_placeholder+=("${format_vars[$i]}")
@@ -521,10 +547,12 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg '${tg_placeholder[${#tg_placeholder[@]}]}' '${1}' - sign is empty."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ]; then
 				echo "Error, -tg '${tg_placeholder[${#tg_placeholder[@]}]}' '${1}' - invalid sign: '${1}'."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			tg_sign+=("${1}")
@@ -533,11 +561,13 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg '${tg_placeholder[${#tg_placeholder[@]}]}' '${tg_sign[${#tg_sign[@]}]}' '${1}' - value is empty."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			if [ "${tg_sign[${#tg_sign[@]}-1]}" != "=" ]; then
 				if ! printf "%d" "${1}" >/dev/null 2>&1; then
 					echo "Error, -tg '${tg_placeholder[${#tg_placeholder[@]}]}' '${tg_sign[${#tg_sign[@]}]}' '${1}' is not a number."
+					echo "Type ${appname} -h for help"
 					exit 1
 				fi
 			fi
@@ -551,6 +581,7 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg <p> - no placeholder specified."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			f=0
@@ -562,6 +593,7 @@ while [ $# -gt 0  ]; do
 			done
 			if [ "${f}" = "0" ]; then
 				echo "Error, -tg '${1}' no such placeholder."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			ti_placeholder+=("${format_vars[$i]}")
@@ -570,10 +602,12 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg '${ti_placeholder[${#ti_placeholder[@]}]}' '${1}' - sign is empty."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ]; then
 				echo "Error, -tg '${ti_placeholder[${#ti_placeholder[@]}]}' '${1}' - invalid sign: '${1}'."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			ti_sign+=("${1}")
@@ -582,11 +616,13 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg '${ti_placeholder[${#ti_placeholder[@]}]}' '${ti_sign[${#ti_sign[@]}]}' '${1}' - value is empty."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			if [ "${ti_sign[${#ti_sign[@]}-1]}" != "=" ]; then
 				if ! printf "%d" "${1}" >/dev/null 2>&1; then
 					echo "Error, -tg '${ti_placeholder[${#ti_placeholder[@]}]}' '${ti_sign[${#ti_sign[@]}]}' '${1}' is not a number."
+					echo "Type ${appname} -h for help"
 					exit 1
 				fi
 			fi
@@ -600,6 +636,7 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg <p> - no placeholder specified."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			f=0
@@ -611,6 +648,7 @@ while [ $# -gt 0  ]; do
 			done
 			if [ "${f}" = "0" ]; then
 				echo "Error, -tg '${1}' no such placeholder."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			tw_placeholder+=("${format_vars[$i]}")
@@ -619,10 +657,12 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg '${tw_placeholder[${#tw_placeholder[@]}]}' '${1}' - sign is empty."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ]; then
 				echo "Error, -tg '${tw_placeholder[${#tw_placeholder[@]}]}' '${1}' - invalid sign: '${1}'."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			tw_sign+=("${1}")
@@ -631,11 +671,13 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg '${tw_placeholder[${#tw_placeholder[@]}]}' '${tw_sign[${#tw_sign[@]}]}' '${1}' - value is empty."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			if [ "${tw_sign[${#tw_sign[@]}-1]}" != "=" ]; then
 				if ! printf "%d" "${1}" >/dev/null 2>&1; then
 					echo "Error, -tg '${tw_placeholder[${#tw_placeholder[@]}]}' '${tw_sign[${#tw_sign[@]}]}' '${1}' is not a number."
+					echo "Type ${appname} -h for help"
 					exit 1
 				fi
 			fi
@@ -649,6 +691,7 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg <p> - no placeholder specified."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			f=0
@@ -660,6 +703,7 @@ while [ $# -gt 0  ]; do
 			done
 			if [ "${f}" = "0" ]; then
 				echo "Error, -tg '${1}' no such placeholder."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			tc_placeholder+=("${format_vars[$i]}")
@@ -668,10 +712,12 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg '${tc_placeholder[${#tc_placeholder[@]}]}' '${1}' - sign is empty."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ]; then
 				echo "Error, -tg '${tc_placeholder[${#tc_placeholder[@]}]}' '${1}' - invalid sign: '${1}'."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			tc_sign+=("${1}")
@@ -680,11 +726,13 @@ while [ $# -gt 0  ]; do
 			shift
 			if [ "${1}" = "" ]; then
 				echo "Error, -tg '${tc_placeholder[${#tc_placeholder[@]}]}' '${tc_sign[${#tc_sign[@]}]}' '${1}' - value is empty."
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			if [ "${tc_sign[${#tc_sign[@]}-1]}" != "=" ]; then
 				if ! printf "%d" "${1}" >/dev/null 2>&1; then
 					echo "Error, -tg '${tc_placeholder[${#tc_placeholder[@]}]}' '${tc_sign[${#tc_sign[@]}]}' '${1}' is not a number."
+					echo "Type ${appname} -h for help"
 					exit 1
 				fi
 			fi
@@ -695,6 +743,11 @@ while [ $# -gt 0  ]; do
 		###
 		-f)
 			shift
+			if [ "${1}" = "" ]; then
+				echo "Error, -f requires a string"
+				echo "Type ${appname} -h for help"
+				exit 1
+			fi
 			format="${1}"
 			;;
 		###
@@ -711,6 +764,7 @@ while [ $# -gt 0  ]; do
 			shift
 			if ! echo "${1}" | grep -qE '#[0-9a-fA-F]{6}' >/dev/null 2>&1; then
 				echo "Error, invalid color string: ${1}"
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			color_def="${1}"
@@ -720,6 +774,7 @@ while [ $# -gt 0  ]; do
 			shift
 			if ! echo "${1}" | grep -qE '#[0-9a-fA-F]{6}' >/dev/null 2>&1; then
 				echo "Error, invalid color string: ${1}"
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			color_good="${1}"
@@ -729,6 +784,7 @@ while [ $# -gt 0  ]; do
 			shift
 			if ! echo "${1}" | grep -qE '#[0-9a-fA-F]{6}' >/dev/null 2>&1; then
 				echo "Error, invalid color string: ${1}"
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			color_warn="${1}"
@@ -738,6 +794,7 @@ while [ $# -gt 0  ]; do
 			shift
 			if ! echo "${1}" | grep -qE '#[0-9a-fA-F]{6}' >/dev/null 2>&1; then
 				echo "Error, invalid color string: ${1}"
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			color_crit="${1}"
@@ -747,6 +804,7 @@ while [ $# -gt 0  ]; do
 			shift
 			if ! echo "${1}" | grep -qE '#[0-9a-fA-F]{6}' >/dev/null 2>&1; then
 				echo "Error, invalid color string: ${1}"
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			color_info="${1}"
@@ -788,7 +846,7 @@ while [ $# -gt 0  ]; do
 			###
 			if [ "${found}" = "0" ]; then
 				echo "Invalid argument: '${1}'"
-				print_usage
+				echo "Type ${appname} -h for help"
 				exit 1
 			fi
 			;;
