module diks: version 1.1

diff --git a/modules/disk b/modules/disk
--- a/modules/disk
+++ b/modules/disk
@@ -2,37 +2,26 @@
 
 ################################################################################
 #
-# CUSTOM VARIABLES
+# CUSTOM PLUGIN SECTION
 #
 ################################################################################
+
+############################################################
+# Variables
+############################################################
 
 ###
 ### Custom Defines
 ###
 appname="disk"
 directory="${BLOCK_INSTANCE:-/}"
-format=" {free} {funit}iB"
-
+format=" {free} {funit}iB free"
 
 
 ###
 ### Thresholds
 ###
-
-# Enable
 has_threshold=1
-
-# Min/Max values
-threshold_min=0
-threshold_max=100
-
-# Default warn/crit values
-threshold_warn="20"
-threshold_crit="10"
-
-# Threshold descriptions (for help display)
-threshold_warn_desc="Specify percent of free disk space for warning (${threshold_min}-${threshold_max})"
-threshold_crit_desc="Specify percent of free disk space for critical (${threshold_min}-${threshold_max})"
 
 
 ###
@@ -99,12 +88,9 @@ format_examples=(
 )
 
 
-
-################################################################################
-#
-# CUSTOM FUNCTIONS
-#
-################################################################################
+############################################################
+# custom_actio function
+############################################################
 
 ###
 ### Evaluate disk space
@@ -125,24 +111,18 @@ custom_action() {
 }
 
 
-status_is_good() {
-	return 1
-}
-status_is_info() {
-	return 1
-}
-status_is_warn() {
-	if [ "${pfree}" -le "${threshold_warn}" ]; then
-		return 0
-	fi
-	return 1
-}
-status_is_crit() {
-	if [ "${pfree}" -le "${threshold_crit}" ]; then
-		return 0
-	fi
-	return 1
-}
+
+
+###
+###
+###
+###    D O   N O T   E D I T   A F T E R   H E R E
+###
+###
+###
+
+
+
 
 ################################################################################
 #
@@ -158,7 +138,6 @@ color_good="#88b090"	# green
 color_warn="#ccdc90"	# yellow
 color_crit="#e89393"	# red
 color_info="#fce94f"	# bright yellow
-
 
 ###
 ### Use of pango markup?
@@ -185,7 +164,6 @@ fi
 # y-coor	${BLOCK_Y}
 
 
-
 ################################################################################
 #
 # BUILT-IN FUNCTIONS
@@ -205,16 +183,17 @@ print_usage() {
 
 	# Show/Hide threshold
 	if [ "${has_threshold}" = "1" ]; then
-		custom_args="${custom_args}[-tw <int>] [-tc <int>] "
+		custom_args="${custom_args}[-tg|-ti|-tw|-tc <p> <s> <int|str>] "
 	fi
 
-	echo "Usage: ${appname} [-f <format>] ${custom_args}"
+	echo "Usage: ${appname} [-f <format>] ${custom_args}[-np] [-cd|-cg|-cw|-cc|-ci <code>]"
 	echo "       ${appname} -h"
 	echo "       ${appname} -v"
 	echo
 
 	if [ "${#custom_args}" -gt "0" ]; then
 		echo "Optional variables:"
+		echo "--------------------------------------------------------------------------------"
 
 		for (( i=0; i<${#arg_params[@]}; i++ )); do
 			printf "  %-13s%s\n" "${arg_params[$i]} ${arg_desc_val[$i]}" "${arg_desc_long[$i]}"
@@ -224,20 +203,57 @@ print_usage() {
 
 	if [ "${has_threshold}" = "1" ]; then
 		echo "Optional threshold arguments:"
-		echo "  -tw <int>    ${threshold_warn_desc}"
-		echo "               Default is: ${threshold_warn}"
-		echo "  -tc <int>    ${threshold_crit_desc}"
-		echo "               Default is: ${threshold_crit}"
+		echo "--------------------------------------------------------------------------------"
+		echo "You can optionally enable threshold checking against any placeholder value."
+		echo "This enables the colorizing of the final output depending on any met"
+		echo "conditions specified."
+		echo "Default is not to use any threshold"
+		echo "  -tg <p> <s> <int|str>   Enable threshold for 'good status'"
+		echo "  -ti <p> <s> <int|str>   Enable threshold for 'info status'"
+		echo "  -tw <p> <s> <int|str>   Enable threshold for 'warn status'"
+		echo "  -tc <p> <s> <int|str>   Enable threshold for 'crit status'"
+		echo
+		echo "   Explanation:"
+		echo "     <p>   is the placeholder value you want to check against."
+		printf "           valid placeholders: "
+		for (( i=0; i<${#format_nodes[@]}; i++ )); do
+			printf "%s" "${format_nodes[$i]} "
+		done
+		printf "\n"
+		echo "           Note 1: placeholder values will be converted to integers"
+		echo "                   Any decimal places will simply be cut off."
+		echo "           Note 2: In equal mode (<s> '=') is a string comparison and"
+		echo "                   no placeholder will be converted."
+		echo "           Note 3: In equal mode (<s> '=') regex is allowed :-)"
+		echo "     <s>   must either be '<', '>' or '=' depending on what direction"
+		echo "           you want to check the threshold placeholder against."
+		echo "     <int> The integer number you want to check against the placeholder."
+		echo "     <str> The string you want to check against the placeholder."
+		echo "           You can only use a string when in equal mode '='."
+		echo "           You can also use regex here."
+		echo
+		echo "   Examples:"
+		echo "     1. Check if value of ${format_nodes[0]} < 50, then format using the good color"
+		echo "     -tg '${format_nodes[0]}' '<' 50"
+		echo
+		echo "     2. Check if value of ${format_nodes[0]} > 90, then format using the warn color"
+		echo "     -tw '${format_nodes[0]}' '>' 90"
+		echo
+		echo "     3. Check if value of ${format_nodes[0]} equals the string 'foo', then format using the info color"
+		echo "     -ti '${format_nodes[0]}' '=' 'foo'"
+		echo
+		echo "     4. Check if value of ${format_nodes[0]} equals the regex '^[0-9]+\$', then format using the info color"
+		echo "     -ti '${format_nodes[0]}' '=' '^[0-9]+\$'"
 		echo
 	fi
 
 	echo "Optional markup (pango):"
-	echo
+	echo "--------------------------------------------------------------------------------"
 	echo "  -np          Disable pango markup"
 	echo
 
 	echo "Optional color arguments:"
-	echo
+	echo "--------------------------------------------------------------------------------"
 	echo "If not specified, script default colors are used"
 	echo "If config file with color codes is present in:"
 	echo "'${HOME}/.config/i3blocks/contrib.conf', these colors will be used."
@@ -255,7 +271,7 @@ print_usage() {
 	echo
 
 	echo "Optional Format placeholders:"
-	echo
+	echo "--------------------------------------------------------------------------------"
 	echo "  Available color placeholders:"
 	echo "  (Use with pango disabled for custom markup) building"
 	echo "     {color}        Current active color depending on thresholds"
@@ -282,7 +298,7 @@ print_usage() {
 }
 
 print_version() {
-	echo "${appname} v1.0 by cytopia"
+	echo "${appname} v1.1 by cytopia"
 	echo "https://github.com/cytopia/i3blocks-modules"
 }
 
@@ -295,24 +311,106 @@ get_status_color() {
 	local _color_warn="${3}"
 	local _color_crit="${4}"
 	local _color_info="${5}"
+
 	# final color
 	local _color="${_color_def}"
 
-	if status_is_good; then
-		_color="${color_good}"
-	fi
-	if status_is_info; then
-		_color="${color_info}"
-	fi
-	if status_is_warn; then
-		_color="${color_warn}"
-	fi
-	if status_is_crit; then
-		_color="${color_crit}"
+	local pval
+
+	# has good color?
+	if [ "${tg_placeholder}" != "" ]; then
+		if [ "${tg_sign}" = "=" ]; then
+			pval="${!tg_placeholder}"
+		else
+			pval="$( echo "${!tg_placeholder}" | grep -oE '[0-9]*' | head -1 )"
+		fi
+
+		if [ "${tg_sign}" = "<" ]; then
+			if [ "${pval}" -lt "${tg_value}" ]; then
+				_color="${color_good}"
+			fi
+		elif [ "${tg_sign}" = "=" ]; then
+			if [[ "${pval}" =~ ${tg_value} ]]; then
+				_color="${color_good}"
+			fi
+		elif [ "${tg_sign}" = ">" ]; then
+			if [ "${pval}" -gt "${tg_value}" ]; then
+				_color="${color_good}"
+			fi
+		fi
 	fi
 
+	# has info color?
+	if [ "${ti_placeholder}" != "" ]; then
+		if [ "${ti_sign}" = "=" ]; then
+			pval="${!ti_placeholder}"
+		else
+			pval="$( echo "${!ti_placeholder}" | grep -oE '[0-9]*' | head -1 )"
+		fi
+
+		if [ "${ti_sign}" = "<" ]; then
+			if [ "${pval}" -lt "${ti_value}" ]; then
+				_color="${color_info}"
+			fi
+		elif [ "${ti_sign}" = "=" ]; then
+			if [[ "${pval}" =~ ${ti_value} ]]; then
+				_color="${color_info}"
+			fi
+		elif [ "${ti_sign}" = ">" ]; then
+			if [ "${pval}" -gt "${ti_value}" ]; then
+				_color="${color_info}"
+			fi
+		fi
+	fi
+
+	# has warn color?
+	if [ "${tw_placeholder}" != "" ]; then
+		if [ "${tw_sign}" = "=" ]; then
+			pval="${!tw_placeholder}"
+		else
+			pval="$( echo "${!tw_placeholder}" | grep -oE '[0-9]*' | head -1 )"
+		fi
+
+		if [ "${tw_sign}" = "<" ]; then
+			if [ "${pval}" -lt "${tw_value}" ]; then
+				_color="${color_warn}"
+			fi
+		elif [ "${tw_sign}" = "=" ]; then
+			if [[ "${pval}" =~ ${tw_value} ]]; then
+				_color="${color_warn}"
+			fi
+		elif [ "${tw_sign}" = ">" ]; then
+			if [ "${pval}" -gt "${tw_value}" ]; then
+				_color="${color_warn}"
+			fi
+		fi
+	fi
+
+	# has crit color?
+	if [ "${tc_placeholder}" != "" ]; then
+		if [ "${tc_sign}" = "=" ]; then
+			pval="${!tc_placeholder}"
+		else
+			pval="$( echo "${!tc_placeholder}" | grep -oE '[0-9]*' | head -1 )"
+		fi
+
+		if [ "${tc_sign}" = "<" ]; then
+			if [ "${pval}" -lt "${tc_value}" ]; then
+				_color="${color_crit}"
+			fi
+		elif [ "${tc_sign}" = "=" ]; then
+			if [[ "${pval}" =~ ${tc_value} ]]; then
+				_color="${color_crit}"
+			fi
+		elif [ "${tc_sign}" = ">" ]; then
+			if [ "${pval}" -gt "${tc_value}" ]; then
+				_color="${color_crit}"
+			fi
+		fi
+	fi
 	echo "${_color}"
 }
+
 
 ###
 ### Replace custom stuff in format string
@@ -369,31 +467,216 @@ fi
 while [ $# -gt 0  ]; do
 	case "$1" in
 		###
-		### Thresholds
+		### Threshold good
+		###
+		-tg${th_chk})
+			tg_placeholder=
+			tg_sign=
+			tg_value=
+
+			# 1/3 Check placeholder
+			shift
+			if [ "${1}" = "" ]; then
+				echo "Error, -tg <p> - no placeholder specified."
+				exit 1
+			fi
+			f=0
+			for (( i=0; i < ${#format_nodes[@]}; i++ )); do
+				if [ "${format_nodes[$i]}" = "${1}" ]; then
+					f=1
+					break
+				fi
+			done
+			if [ "${f}" = "0" ]; then
+				echo "Error, -tg '${1}' no such placeholder."
+				exit 1
+			fi
+			tg_placeholder="${format_vars[$i]}"
+
+			# 2/3 Check sign
+			shift
+			if [ "${1}" = "" ]; then
+				echo "Error, -tg '${tg_placeholder}' '${1}' - sign is empty."
+				exit 1
+			fi
+			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ]; then
+				echo "Error, -tg '${tg_placeholder}' '${1}' - invalid sign: '${1}'."
+				exit 1
+			fi
+			tg_sign="${1}"
+
+			# 3/3 Check value
+			shift
+			if [ "${1}" = "" ]; then
+				echo "Error, -tg '${tg_placeholder}' '${tg_sign}' '${1}' - value is empty."
+				exit 1
+			fi
+			if [ "${tg_sign}" != "=" ]; then
+				if ! printf "%d" "${1}" >/dev/null 2>&1; then
+					echo "Error, -tg '${tg_placeholder}' '${tg_sign}' '${1}' is not a number."
+					exit 1
+				fi
+			fi
+			tg_value="${1}"
+			;;
+		###
+		### Threshold info
+		###
+		-ti${th_chk})
+			ti_placeholder=
+			ti_sign=
+			ti_value=
+
+			# 1/3 Check placeholder
+			shift
+			if [ "${1}" = "" ]; then
+				echo "Error, -ti <p> - no placeholder specified."
+				exit 1
+			fi
+			f=0
+			for (( i=0; i < ${#format_nodes[@]}; i++ )); do
+				if [ "${format_nodes[$i]}" = "${1}" ]; then
+					f=1
+					break
+				fi
+			done
+			if [ "${f}" = "0" ]; then
+				echo "Error, -ti '${1}' no such placeholder."
+				exit 1
+			fi
+			ti_placeholder="${format_vars[$i]}"
+
+			# 2/3 Check sign
+			shift
+			if [ "${1}" = "" ]; then
+				echo "Error, -ti '${ti_placeholder}' '${1}' - sign is empty."
+				exit 1
+			fi
+			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ]; then
+				echo "Error, -ti '${ti_placeholder}' '${1}' - invalid sign: '${1}'."
+				exit 1
+			fi
+			ti_sign="${1}"
+
+			# 3/3 Check value
+			shift
+			if [ "${1}" = "" ]; then
+				echo "Error, -ti '${ti_placeholder}' '${ti_sign}' '${1}' - value is empty."
+				exit 1
+			fi
+			if [ "${ti_sign}" != "=" ]; then
+				if ! printf "%d" "${1}" >/dev/null 2>&1; then
+					echo "Error, -ti '${ti_placeholder}' '${ti_sign}' '${1}' is not a number."
+					exit 1
+				fi
+			fi
+			ti_value="${1}"
+			;;
+		###
+		### Threshold warn
 		###
 		-tw${th_chk})
+			tw_placeholder=
+			tw_sign=
+			tw_value=
+
+			# 1/3 Check placeholder
 			shift
-			if ! printf "%d" "${1}" >/dev/null 2>&1; then
-				echo "Error, -tw ${1} is not a number."
+			if [ "${1}" = "" ]; then
+				echo "Error, -tw <p> - no placeholder specified."
 				exit 1
 			fi
-			if [ "${1}" -lt "${threshold_min}" ] || [ "${1}" -gt "${threshold_max}" ]; then
-				echo "Error, -tw ${1} is not in range (0-100)."
+			f=0
+			for (( i=0; i < ${#format_nodes[@]}; i++ )); do
+				if [ "${format_nodes[$i]}" = "${1}" ]; then
+					f=1
+					break
+				fi
+			done
+			if [ "${f}" = "0" ]; then
+				echo "Error, -tw '${1}' no such placeholder."
 				exit 1
 			fi
-			threshold_warn="${1}"
+			tw_placeholder="${format_vars[$i]}"
+
+			# 2/3 Check sign
+			shift
+			if [ "${1}" = "" ]; then
+				echo "Error, -tw '${tw_placeholder}' '${1}' - sign is empty."
+				exit 1
+			fi
+			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ]; then
+				echo "Error, -tw '${tw_placeholder}' '${1}' - invalid sign: '${1}'."
+				exit 1
+			fi
+			tw_sign="${1}"
+
+			# 3/3 Check value
+			shift
+			if [ "${1}" = "" ]; then
+				echo "Error, -tw '${tw_placeholder}' '${tw_sign}' '${1}' - value is empty."
+				exit 1
+			fi
+			if [ "${tw_sign}" != "=" ]; then
+				if ! printf "%d" "${1}" >/dev/null 2>&1; then
+					echo "Error, -tw '${tw_placeholder}' '${tw_sign}' '${1}' is not a number."
+					exit 1
+				fi
+			fi
+			tw_value="${1}"
 			;;
+		###
+		### Threshold crit
+		###
 		-tc${th_chk})
+			tc_placeholder=
+			tc_sign=
+			tc_value=
+
+			# 1/3 Check placeholder
 			shift
-			if ! printf "%d" "${1}" >/dev/null 2>&1; then
-				echo "Error, -tc ${1} is not a number."
+			if [ "${1}" = "" ]; then
+				echo "Error, -tc <p> - no placeholder specified."
 				exit 1
 			fi
-			if [ "${1}" -lt "${threshold_min}" ] || [ "${1}" -gt "${threshold_max}" ]; then
-				echo "Error, -tc ${1} is not in range (0-100)."
+			f=0
+			for (( i=0; i < ${#format_nodes[@]}; i++ )); do
+				if [ "${format_nodes[$i]}" = "${1}" ]; then
+					f=1
+					break
+				fi
+			done
+			if [ "${f}" = "0" ]; then
+				echo "Error, -tc '${1}' no such placeholder."
 				exit 1
 			fi
-			threshold_crit="${1}"
+			tc_placeholder="${format_vars[$i]}"
+
+			# 2/3 Check sign
+			shift
+			if [ "${1}" = "" ]; then
+				echo "Error, -tc '${tc_placeholder}' '${1}' - sign is empty."
+				exit 1
+			fi
+			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ]; then
+				echo "Error, -tc '${tc_placeholder}' '${1}' - invalid sign: '${1}'."
+				exit 1
+			fi
+			tc_sign="${1}"
+
+			# 3/3 Check value
+			shift
+			if [ "${1}" = "" ]; then
+				echo "Error, -tc '${tc_placeholder}' '${tw_sign}' '${1}' - value is empty."
+				exit 1
+			fi
+			if [ "${tc_sign}" != "=" ]; then
+				if ! printf "%d" "${1}" >/dev/null 2>&1; then
+					echo "Error, -tc '${tc_placeholder}' '${tc_sign}' '${1}' is not a number."
+					exit 1
+				fi
+			fi
+			tc_value="${1}"
 			;;
 		###
 		### Format overwrite
