memory: version 1.7

diff --git a/modules/memory b/modules/memory
--- a/modules/memory
+++ b/modules/memory
@@ -126,7 +126,6 @@ custom_action() {
 
 
 
-
 ################################################################################
 #
 # BUILT-IN VARIABLES
@@ -141,6 +140,14 @@ color_good="#88b090"	# green
 color_warn="#ccdc90"	# yellow
 color_crit="#e89393"	# red
 color_info="#fce94f"	# bright yellow
+
+###
+### Extended format arrays
+###
+fe_placeholder=()
+fe_sign=()
+fe_value=()
+fe_format=()
 
 
 ###
@@ -210,7 +217,7 @@ print_usage() {
 		custom_args="${custom_args}[-tg|-ti|-tw|-tc <p> <s> <int|str>] "
 	fi
 
-	echo "Usage: ${appname} [-f <format>] ${custom_args}[-np] [-cd|-cg|-cw|-cc|-ci <code>]"
+	echo "Usage: ${appname} [-f <format>] [-fe <p> <s> <int|str> <f>] ${custom_args}[-np] [-cd|-cg|-cw|-cc|-ci <code>]"
 	echo "       ${appname} -h"
 	echo "       ${appname} -v"
 	echo
@@ -249,10 +256,12 @@ print_usage() {
 		printf "\n"
 		echo "           Note 1: placeholder values will be converted to integers"
 		echo "                   Any decimal places will simply be cut off."
-		echo "           Note 2: In equal mode (<s> '=') is a string comparison and"
+		echo "           Note 2: In equal mode (<s> '=') is a string regex comparison and"
+		echo "                   no placeholder will be converted."
+		echo "           Note 3: In unequal mode (<s> '!=') is a string comparison and"
 		echo "                   no placeholder will be converted."
 		echo "           Note 3: In equal mode (<s> '=') regex is allowed :-)"
-		echo "     <s>   must either be '<', '>' or '=' depending on what direction"
+		echo "     <s>   must either be '<', '>', '=' or '!='  depending on what direction"
 		echo "           you want to check the threshold placeholder against."
 		echo "     <int> The integer number you want to check against the placeholder."
 		echo "     <str> The string you want to check against the placeholder."
@@ -322,10 +331,44 @@ print_usage() {
 	done
 	echo "  Default:"
 	echo "     -f \"${format}\""
+	echo
+
+	echo "Optional extended Format output:"
+	echo "--------------------------------------------------------------------------------"
+	echo "You can conditionally set your output text depending on the value of any placeholder."
+	echo "For example, If you have a placeholder {status} that either is 'up' or 'down', you"
+	echo "can specify different outputs for 'up' and for 'down'."
+	echo "Usage"
+	echo "  -fe <p> <s> <v> <f>"
+	echo
+	echo "   Format example:"
+	echo "     -fe '{status} '=' 'up' 'It works ;-)' -fe '{status}' '!=' 'up' 'status is: {status}'"
+	echo "   Explanation:"
+	echo "     <p>   is the placeholder value you want to check against."
+	printf "           valid placeholders: "
+	for (( i=0; i<${#format_nodes[@]}; i++ )); do
+		printf "%s" "${format_nodes[$i]} "
+	done
+	printf "\n"
+	echo "           Note 1: placeholder values will be converted to integers"
+	echo "                   Any decimal places will simply be cut off."
+	echo "           Note 2: In equal mode (<s> '=') is a string regex comparison and"
+	echo "                   no placeholder will be converted."
+	echo "           Note 3: In unequal mode (<s> '!=') is a string comparison and"
+	echo "                   no placeholder will be converted."
+	echo "           Note 3: In equal mode (<s> '=') regex is allowed :-)"
+	echo "     <s>   must either be '<', '>', '=' or '!='  depending on what direction"
+	echo "           you want to check the threshold placeholder against."
+	echo "     <int> The integer number you want to check against the placeholder."
+	echo "     <str> The string you want to check against the placeholder."
+	echo "           You can only use a string when in equal mode '='."
+	echo "           You can also use regex here."
+	echo "     <f>   Is the format string that should be displayed under the above condition."
+	echo "           Of course you can also use placeholders here ;-)."
 }
 
 print_version() {
-	echo "${appname} v1.6 by cytopia"
+	echo "${appname} v1.7 by cytopia"
 	echo "https://github.com/cytopia/i3blocks-modules"
 }
 
@@ -366,7 +409,7 @@ get_status_color() {
 	# has good color?
 	for (( i=0; i < ${#tg_placeholder[@]}; i++ )); do
 
-		if [ "${tg_sign[$i]}" = "=" ]; then
+		if [ "${tg_sign[$i]}" = "=" ] || [ "${tg_sign[$i]}" = "!=" ]; then
 			pval="${!tg_placeholder[$i]}"
 		else
 			pval="$( echo "${!tg_placeholder[$i]}" | grep -oE '[0-9]*' | head -1 )"
@@ -380,6 +423,10 @@ get_status_color() {
 			if [[ "${pval}" =~ ${tg_value[$i]} ]]; then
 				_color="${_color_good}"
 			fi
+		elif [ "${tg_sign[$i]}" = "!=" ]; then
+			if [[ "${pval}" != ${tg_value[$i]} ]]; then
+				_color="${_color_good}"
+			fi
 		elif [ "${tg_sign[$i]}" = ">" ]; then
 			if [ "${pval}" -gt "${tg_value[$i]}" ]; then
 				_color="${_color_good}"
@@ -389,7 +436,7 @@ get_status_color() {
 	# has info color?
 	for (( i=0; i < ${#ti_placeholder[@]}; i++ )); do
 
-		if [ "${ti_sign[$i]}" = "=" ]; then
+		if [ "${ti_sign[$i]}" = "=" ] || [ "${ti_sign[$i]}" = "!=" ]; then
 			pval="${!ti_placeholder[$i]}"
 		else
 			pval="$( echo "${!ti_placeholder[$i]}" | grep -oE '[0-9]*' | head -1 )"
@@ -403,6 +450,10 @@ get_status_color() {
 			if [[ "${pval}" =~ ${ti_value[$i]} ]]; then
 				_color="${_color_info}"
 			fi
+		elif [ "${ti_sign[$i]}" = "!=" ]; then
+			if [[ "${pval}" != ${ti_value[$i]} ]]; then
+				_color="${_color_info}"
+			fi
 		elif [ "${ti_sign[$i]}" = ">" ]; then
 			if [ "${pval}" -gt "${ti_value[$i]}" ]; then
 				_color="${_color_info}"
@@ -412,7 +463,7 @@ get_status_color() {
 	# has warning color?
 	for (( i=0; i < ${#tw_placeholder[@]}; i++ )); do
 
-		if [ "${tw_sign[$i]}" = "=" ]; then
+		if [ "${tw_sign[$i]}" = "=" ] || [ "${tw_sign[$i]}" = "!=" ]; then
 			pval="${!tw_placeholder[$i]}"
 		else
 			pval="$( echo "${!tw_placeholder[$i]}" | grep -oE '[0-9]*' | head -1 )"
@@ -426,6 +477,10 @@ get_status_color() {
 			if [[ "${pval}" =~ ${tw_value[$i]} ]]; then
 				_color="${_color_warn}"
 			fi
+		elif [ "${tw_sign[$i]}" = "!=" ]; then
+			if [[ "${pval}" != ${tw_value[$i]} ]]; then
+				_color="${_color_warn}"
+			fi
 		elif [ "${tw_sign[$i]}" = ">" ]; then
 			if [ "${pval}" -gt "${tw_value[$i]}" ]; then
 				_color="${_color_warn}"
@@ -437,7 +492,7 @@ get_status_color() {
 	# has critical color?
 	for (( i=0; i < ${#tc_placeholder[@]}; i++ )); do
 
-		if [ "${tc_sign[$i]}" = "=" ]; then
+		if [ "${tc_sign[$i]}" = "=" ] || [ "${tc_sign[$i]}" = "!=" ]; then
 			pval="${!tc_placeholder[$i]}"
 		else
 			pval="$( echo "${!tc_placeholder[$i]}" | grep -oE '[0-9]*' | head -1 )"
@@ -449,6 +504,10 @@ get_status_color() {
 			fi
 		elif [ "${tc_sign[$i]}" = "=" ]; then
 			if [[ "${pval}" =~ ${tc_value[$i]} ]]; then
+				_color="${_color_crit}"
+			fi
+		elif [ "${tc_sign[$i]}" = "!=" ]; then
+			if [[ "${pval}" != ${tc_value[$i]} ]]; then
 				_color="${_color_crit}"
 			fi
 		elif [ "${tc_sign[$i]}" = ">" ]; then
@@ -471,6 +530,37 @@ replace_placeholders() {
 	local _search
 	local _replace
 
+	# Select format based on extended placeholders
+	for (( i=0; i < ${#fe_placeholder[@]}; i++ )); do
+
+		if [ "${fe_sign[$i]}" = "=" ] || [ "${fe_sign[$i]}" = "!=" ]; then
+			pval="${!fe_placeholder[$i]}"
+		else
+			pval="$( echo "${!fe_placeholder[$i]}" | grep -oE '[0-9]*' | head -1 )"
+		fi
+
+		if [ "${fe_sign[$i]}" = "<" ]; then
+			if [ "${pval}" -lt "${fe_value[$i]}" ]; then
+				_format="${fe_format[$i]}"
+			fi
+		elif [ "${fe_sign[$i]}" = "=" ]; then
+			if [[ "${pval}" =~ ${fe_value[$i]} ]]; then
+				_format="${fe_format[$i]}"
+			fi
+		elif [ "${fe_sign[$i]}" = "!=" ]; then
+			if [[ "${pval}" != ${fe_value[$i]} ]]; then
+				_format="${fe_format[$i]}"
+			fi
+		elif [ "${fe_sign[$i]}" = ">" ]; then
+			if [ "${pval}" -gt "${fe_value[$i]}" ]; then
+				_format="${fe_format[$i]}"
+			fi
+		fi
+	done
+
+
+
+	# Replace placeholders in $format
 	for (( i=0; i < ${#format_nodes[@]}; i++ )); do
 		_search="${format_nodes[$i]}"
 		_replace="${!format_vars[$i]}"
@@ -521,6 +611,70 @@ fi
 while [ $# -gt 0  ]; do
 	case "$1" in
 		###
+		### Extended formats
+		###
+		-fe)
+			# 1/4 Check placeholder
+			shift
+			if [ "${1}" = "" ]; then
+				echo "Error, -fe <p> - no placeholder specified."
+				echo "Type ${appname} -h for help"
+				exit 1
+			fi
+			f=0
+			for (( i=0; i < ${#format_nodes[@]}; i++ )); do
+				if [ "${format_nodes[$i]}" = "${1}" ]; then
+					f=1
+					break
+				fi
+			done
+			if [ "${f}" = "0" ]; then
+				echo "Error, -fe '${1}' no such placeholder."
+				echo "Type ${appname} -h for help"
+				exit 1
+			fi
+			fe_placeholder+=("${format_vars[$i]}")
+
+			# 2/4 Check sign
+			shift
+			if [ "${1}" = "" ]; then
+				echo "Error, -fe '{${fe_placeholder[${#fe_placeholder[@]}-1]}}' '${1}' - sign argyment is empty."
+				echo "Type ${appname} -h for help"
+				exit 1
+			fi
+			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ] && [ "${1}" != "!=" ]; then
+				echo "Error, -fe '{${fe_placeholder[${#fe_placeholder[@]}-1]}}' '${1}' - invalid sign: '${1}'."
+				echo "Type ${appname} -h for help"
+				exit 1
+			fi
+			fe_sign+=("${1}")
+
+			# 3/4 Check value
+			shift
+			if [ "${1}" = "" ]; then
+				echo "Error, -fe '{${fe_placeholder[${#fe_placeholder[@]}-1]}}' '${fe_sign[${#fe_sign[@]}-1]}' '${1}' - value argument is empty."
+				echo "Type ${appname} -h for help"
+				exit 1
+			fi
+			if [ "${fe_sign[${#fe_sign[@]}-1]}" = ">" ] || [ "${fe_sign[${#fe_sign[@]}-1]}" = "<" ]; then
+				if ! printf "%d" "${1}" >/dev/null 2>&1; then
+					echo "Error, -fe '{${fe_placeholder[${#fe_placeholder[@]}-1]}}' '${fe_sign[${#fe_sign[@]}-1]}' '${1}' - value argument is not a number."
+					echo "Type ${appname} -h for help"
+					exit 1
+				fi
+			fi
+			fe_value+=("${1}")
+
+			# 4/4 Check placeholder string
+			shift
+			if [ "${1}" = "" ]; then
+				echo "Error, -fe '{${fe_placeholder[${#fe_placeholder[@]}-1]}}' '${fe_sign[${#fe_sign[@]}-1]}' '${fe_value[${#fe_value[@]}-1]}' - format argument is empty."
+				echo "Type ${appname} -h for help"
+				exit 1
+			fi
+			fe_format+=("${1}")
+			;;
+		###
 		### Threshold good
 		###
 		-tg${th_chk})
@@ -548,12 +702,12 @@ while [ $# -gt 0  ]; do
 			# 2/3 Check sign
 			shift
 			if [ "${1}" = "" ]; then
-				echo "Error, -tg '${tg_placeholder[${#tg_placeholder[@]}]}' '${1}' - sign is empty."
+				echo "Error, -tg '{${tg_placeholder[${#tg_placeholder[@]}-1]}}' '${1}' - sign argument is empty."
 				echo "Type ${appname} -h for help"
 				exit 1
 			fi
-			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ]; then
-				echo "Error, -tg '${tg_placeholder[${#tg_placeholder[@]}]}' '${1}' - invalid sign: '${1}'."
+			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ] && [ "${1}" != "!=" ]; then
+				echo "Error, -tg '{${tg_placeholder[${#tg_placeholder[@]}-1]}}' '${1}' - invalid sign: '${1}'."
 				echo "Type ${appname} -h for help"
 				exit 1
 			fi
@@ -562,13 +716,13 @@ while [ $# -gt 0  ]; do
 			# 3/3 Check value
 			shift
 			if [ "${1}" = "" ]; then
-				echo "Error, -tg '${tg_placeholder[${#tg_placeholder[@]}]}' '${tg_sign[${#tg_sign[@]}]}' '${1}' - value is empty."
+				echo "Error, -tg '{${tg_placeholder[${#tg_placeholder[@]}-1]}}' '${tg_sign[${#tg_sign[@]}-1]}' '${1}' - value argyment is empty."
 				echo "Type ${appname} -h for help"
 				exit 1
 			fi
-			if [ "${tg_sign[${#tg_sign[@]}-1]}" != "=" ]; then
+			if [ "${tg_sign[${#tg_sign[@]}-1]}" = ">" ] || [ "${tg_sign[${#tg_sign[@]}-1]}" = "<" ]; then
 				if ! printf "%d" "${1}" >/dev/null 2>&1; then
-					echo "Error, -tg '${tg_placeholder[${#tg_placeholder[@]}]}' '${tg_sign[${#tg_sign[@]}]}' '${1}' is not a number."
+					echo "Error, -tg '{${tg_placeholder[${#tg_placeholder[@]}-1]}}' '${tg_sign[${#tg_sign[@]}-1]}' '${1}' - value argument is not a number."
 					echo "Type ${appname} -h for help"
 					exit 1
 				fi
@@ -582,7 +736,7 @@ while [ $# -gt 0  ]; do
 			# 1/3 Check placeholder
 			shift
 			if [ "${1}" = "" ]; then
-				echo "Error, -tg <p> - no placeholder specified."
+				echo "Error, -ti <p> - no placeholder specified."
 				echo "Type ${appname} -h for help"
 				exit 1
 			fi
@@ -594,7 +748,7 @@ while [ $# -gt 0  ]; do
 				fi
 			done
 			if [ "${f}" = "0" ]; then
-				echo "Error, -tg '${1}' no such placeholder."
+				echo "Error, -ti '${1}' no such placeholder."
 				echo "Type ${appname} -h for help"
 				exit 1
 			fi
@@ -603,12 +757,12 @@ while [ $# -gt 0  ]; do
 			# 2/3 Check sign
 			shift
 			if [ "${1}" = "" ]; then
-				echo "Error, -tg '${ti_placeholder[${#ti_placeholder[@]}]}' '${1}' - sign is empty."
+				echo "Error, -ti '{${ti_placeholder[${#ti_placeholder[@]}-1]}}' '${1}' - sign argument is empty."
 				echo "Type ${appname} -h for help"
 				exit 1
 			fi
-			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ]; then
-				echo "Error, -tg '${ti_placeholder[${#ti_placeholder[@]}]}' '${1}' - invalid sign: '${1}'."
+			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ] && [ "${1}" != "!=" ]; then
+				echo "Error, -ti '{${ti_placeholder[${#ti_placeholder[@]}-1]}}' '${1}' - invalid sign: '${1}'."
 				echo "Type ${appname} -h for help"
 				exit 1
 			fi
@@ -617,13 +771,13 @@ while [ $# -gt 0  ]; do
 			# 3/3 Check value
 			shift
 			if [ "${1}" = "" ]; then
-				echo "Error, -tg '${ti_placeholder[${#ti_placeholder[@]}]}' '${ti_sign[${#ti_sign[@]}]}' '${1}' - value is empty."
+				echo "Error, -ti '{${ti_placeholder[${#ti_placeholder[@]}-1]}}' '${ti_sign[${#ti_sign[@]}-1]}' '${1}' - value argyment is empty."
 				echo "Type ${appname} -h for help"
 				exit 1
 			fi
-			if [ "${ti_sign[${#ti_sign[@]}-1]}" != "=" ]; then
+			if [ "${ti_sign[${#ti_sign[@]}-1]}" = ">" ] || [ "${ti_sign[${#ti_sign[@]}-1]}" = "<" ]; then
 				if ! printf "%d" "${1}" >/dev/null 2>&1; then
-					echo "Error, -tg '${ti_placeholder[${#ti_placeholder[@]}]}' '${ti_sign[${#ti_sign[@]}]}' '${1}' is not a number."
+					echo "Error, -ti '{${ti_placeholder[${#ti_placeholder[@]}-1]}}' '${ti_sign[${#ti_sign[@]}-1]}' '${1}' - value argument is not a number."
 					echo "Type ${appname} -h for help"
 					exit 1
 				fi
@@ -637,7 +791,7 @@ while [ $# -gt 0  ]; do
 			# 1/3 Check placeholder
 			shift
 			if [ "${1}" = "" ]; then
-				echo "Error, -tg <p> - no placeholder specified."
+				echo "Error, -tw <p> - no placeholder specified."
 				echo "Type ${appname} -h for help"
 				exit 1
 			fi
@@ -649,7 +803,7 @@ while [ $# -gt 0  ]; do
 				fi
 			done
 			if [ "${f}" = "0" ]; then
-				echo "Error, -tg '${1}' no such placeholder."
+				echo "Error, -tw '${1}' no such placeholder."
 				echo "Type ${appname} -h for help"
 				exit 1
 			fi
@@ -658,12 +812,12 @@ while [ $# -gt 0  ]; do
 			# 2/3 Check sign
 			shift
 			if [ "${1}" = "" ]; then
-				echo "Error, -tg '${tw_placeholder[${#tw_placeholder[@]}]}' '${1}' - sign is empty."
+				echo "Error, -tw '{${tw_placeholder[${#tw_placeholder[@]}-1]}}' '${1}' - sign argument is empty."
 				echo "Type ${appname} -h for help"
 				exit 1
 			fi
-			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ]; then
-				echo "Error, -tg '${tw_placeholder[${#tw_placeholder[@]}]}' '${1}' - invalid sign: '${1}'."
+			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ] && [ "${1}" != "!=" ]; then
+				echo "Error, -tw '{${tw_placeholder[${#tw_placeholder[@]}-1]}}' '${1}' - invalid sign: '${1}'."
 				echo "Type ${appname} -h for help"
 				exit 1
 			fi
@@ -672,13 +826,13 @@ while [ $# -gt 0  ]; do
 			# 3/3 Check value
 			shift
 			if [ "${1}" = "" ]; then
-				echo "Error, -tg '${tw_placeholder[${#tw_placeholder[@]}]}' '${tw_sign[${#tw_sign[@]}]}' '${1}' - value is empty."
+				echo "Error, -tw '{${tw_placeholder[${#tw_placeholder[@]}-1]}}' '${tw_sign[${#tw_sign[@]}-1]}' '${1}' - value argyment is empty."
 				echo "Type ${appname} -h for help"
 				exit 1
 			fi
-			if [ "${tw_sign[${#tw_sign[@]}-1]}" != "=" ]; then
+			if [ "${tw_sign[${#tw_sign[@]}-1]}" = ">" ] || [ "${tw_sign[${#tw_sign[@]}-1]}" = "<" ]; then
 				if ! printf "%d" "${1}" >/dev/null 2>&1; then
-					echo "Error, -tg '${tw_placeholder[${#tw_placeholder[@]}]}' '${tw_sign[${#tw_sign[@]}]}' '${1}' is not a number."
+					echo "Error, -tw '{${tw_placeholder[${#tw_placeholder[@]}-1]}}' '${tw_sign[${#tw_sign[@]}-1]}' '${1}' - value argument is not a number."
 					echo "Type ${appname} -h for help"
 					exit 1
 				fi
@@ -692,7 +846,7 @@ while [ $# -gt 0  ]; do
 			# 1/3 Check placeholder
 			shift
 			if [ "${1}" = "" ]; then
-				echo "Error, -tg <p> - no placeholder specified."
+				echo "Error, -tc <p> - no placeholder specified."
 				echo "Type ${appname} -h for help"
 				exit 1
 			fi
@@ -704,7 +858,7 @@ while [ $# -gt 0  ]; do
 				fi
 			done
 			if [ "${f}" = "0" ]; then
-				echo "Error, -tg '${1}' no such placeholder."
+				echo "Error, -tc '${1}' no such placeholder."
 				echo "Type ${appname} -h for help"
 				exit 1
 			fi
@@ -713,12 +867,12 @@ while [ $# -gt 0  ]; do
 			# 2/3 Check sign
 			shift
 			if [ "${1}" = "" ]; then
-				echo "Error, -tg '${tc_placeholder[${#tc_placeholder[@]}]}' '${1}' - sign is empty."
+				echo "Error, -tc '{${tc_placeholder[${#tc_placeholder[@]}-1]}}' '${1}' - sign argument is empty."
 				echo "Type ${appname} -h for help"
 				exit 1
 			fi
-			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ]; then
-				echo "Error, -tg '${tc_placeholder[${#tc_placeholder[@]}]}' '${1}' - invalid sign: '${1}'."
+			if [ "${1}" != "<" ] && [ "${1}" != ">" ] && [ "${1}" != "=" ] && [ "${1}" != "!=" ]; then
+				echo "Error, -tc '{${tc_placeholder[${#tc_placeholder[@]}-1]}}' '${1}' - invalid sign: '${1}'."
 				echo "Type ${appname} -h for help"
 				exit 1
 			fi
@@ -727,13 +881,13 @@ while [ $# -gt 0  ]; do
 			# 3/3 Check value
 			shift
 			if [ "${1}" = "" ]; then
-				echo "Error, -tg '${tc_placeholder[${#tc_placeholder[@]}]}' '${tc_sign[${#tc_sign[@]}]}' '${1}' - value is empty."
+				echo "Error, -tc '{${tc_placeholder[${#tc_placeholder[@]}-1]}}' '${tc_sign[${#tc_sign[@]}-1]}' '${1}' - value argyment is empty."
 				echo "Type ${appname} -h for help"
 				exit 1
 			fi
-			if [ "${tc_sign[${#tc_sign[@]}-1]}" != "=" ]; then
+			if [ "${tc_sign[${#tc_sign[@]}-1]}" = ">" ] || [ "${tc_sign[${#tc_sign[@]}-1]}" = "<" ]; then
 				if ! printf "%d" "${1}" >/dev/null 2>&1; then
-					echo "Error, -tg '${tc_placeholder[${#tc_placeholder[@]}]}' '${tc_sign[${#tc_sign[@]}]}' '${1}' is not a number."
+					echo "Error, -tc '{${tc_placeholder[${#tc_placeholder[@]}-1]}}' '${tc_sign[${#tc_sign[@]}-1]}' '${1}' - value argument is not a number."
 					echo "Type ${appname} -h for help"
 					exit 1
 				fi
